### PR TITLE
Migrate from `maven-artifact-transfer` to direct use of Resolver API

### LINKED ISSUE #64: Migrate from `maven-artifact-transfer` to direct use of Resolver API
As explained in https://github.com/mojohaus/flatten-maven-plugin/pull/336#discussion_r1170517630, `maven-artifact-transfer` is deprecated and the Maven developers currently recommend using the Resolver API directly.

That is, side-port https://github.com/jenkinsci/maven-hpi-plugin/pull/506 to this repository.

### PR DESCRIPTION
**Pull request by pyatizbyantsevia**
Fixes #64

### Testing done

I tested the plugin in action by running a simple project that reflects how it works: https://github.com/pyatizbyantsevia/jellydoc-maven-plugin-64

### Submitter checklist
- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [x] Link to relevant issues in GitHub or Jira
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [x] Ensure you have provided tests - that demonstrates feature works or fixes the issue

### Other

I'm not sure if using RepositoryUtils methods is a good idea. The description of this class contains the following comment:
*Warning: This is an internal utility class that is only public for technical reasons, it is not part of the public API. In particular, this class can be changed or deleted without prior notice.*

### CODE REVIEW

**Comment by pyatizbyantsevia** [comment]
@basil, please take a look

It would be great to close this as part of Hacktoberfest

**Review by olamy — APPROVED** [review]

**Review by basil — APPROVED** [review]
Thanks for the PR!

**Comment by basil** [comment]
@pyatizbyantsevia It's superfluous to say that we're grateful for you cleaning up this old Maven plugin. If you're interested in another ticket like this, https://github.com/jenkinsci/maven-hpi-plugin/issues/511 is still open. If not, then thanks again for this contribution!

**Comment by pyatizbyantsevia** [comment]
I want to express my gratitude to everyone involved! It was an interesting experience =)

**Pull request merged**
